name: deploy-prod-content

on:
  workflow_dispatch:
    inputs:
      locale:
        required: true
        type: choice
        description: 'Locale to deploys'
        default: 'en-us'
        options:
        - en-us
        - es-cl
        - pl-pl

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: "${{ github.event.inputs.locale }}-build"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
    - name: "build"
      run: |
        sleep 30
      shell: bash

  swap-slot:
    name: "${{ github.event.inputs.locale }}-swap-slot"
    runs-on: ubuntu-latest
    needs: build
    environment: prod-content
    steps:
    - name: "deploy"
      run: |
        sleep 30
      shell: bash
